name: release-test

on:
  workflow_dispatch:

jobs:
  golangci-lint:
    uses: ./.github/workflows/golangci-lint.yml

  release-test:
    name: release-test
    permissions:
      contents: write
      id-token: write
    runs-on: macos-latest
    needs: golangci-lint
    steps:
      - name: Check out PR code
        uses: actions/checkout@v6
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0 # GoReleaser requires git history

      - name: Setup Linux OS dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y xorg-dev libgl1-mesa-dev libglu1-mesa-dev

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.25'
          cache: true

      - name: Setup Go environment
        run: |
          go env -w GOFLAGS="-buildvcs=false"

      - name: Install Cosign
        uses: sigstore/cosign-installer@v4.0.0

      - name: Run GoReleaser (Snapshot)
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: '~> v2'
          args: release --snapshot --clean --skip=publish --verbose
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
